"""
fetch_icons.py — download openly-licensed character icons (OpenMoji,
CC BY-SA 4.0, https://openmoji.org) to replace the emoji placeholders.

OpenMoji is distributed on GitHub/CDN precisely for this kind of use;
only attribution is required (already noted in public/icons/README.md
and the game's main menu).

Usage:  python tools/fetch_icons.py
Output: public/icons/openmoji/<slug>.svg  +  src/data/iconOverrides.ts
"""

import pathlib
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "public" / "icons" / "openmoji"
OVERRIDES_TS = ROOT / "src" / "data" / "iconOverrides.ts"

CDN = "https://cdn.jsdelivr.net/gh/hfg-gmuend/openmoji@15.0.0/color/svg/{}.svg"

# game emoji -> slug, or (slug, art_emoji) when better-matching art exists.
# Design Matrix reference:
#   Tatay Ben  — salakot + working shirt (custom Flaticon icon, see CUSTOM_FIRST)
#   Ate Lalay  — apron + small notebook  -> interim art: woman cook (apron)
#   Kuya Onyok — clipboard + festival shirt -> interim art: man teacher (board)
EMOJI = {
    "\U0001F468\U0001F3FD‍\U0001F33E": "farmer",       # man farmer, medium skin
    "\U0001F469\U0001F3FD‍\U0001F4BC": ("storekeeper", "\U0001F469\U0001F3FD‍\U0001F373"),
    "\U0001F57A\U0001F3FD": ("organizer", "\U0001F468\U0001F3FD‍\U0001F3EB"),
    "\U0001F466\U0001F3FD": "boy",
    "\U0001F467\U0001F3FD": "girl",
    "\U0001F9D2\U0001F3FD": "child",
    "\U0001F475\U0001F3FD": "lola",                         # older woman customer
    "\U0001F392": "backpack",
    "\U0001F989": "owl",
    "\U0001F43F️": "squirrel",
    "\U0001F407": "rabbit",
    "\U0001F403": "carabao",                                # water buffalo
    "\U0001F994": "hedgehog",
    "\U0001F438": "frog",
    "\U0001F98C": "deer",
    "\U0001F430": "bunny-face",
}

SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}

# user-provided icons (e.g. downloaded from Flaticon under the user's own
# license) that take priority over the OpenMoji fallback, keyed by slug
CUSTOM_FIRST = {
    "farmer": "/icons/farmer-ben.png",            # Tatay Ben (already downloaded)
    "storekeeper": "/icons/storekeeper-lalay.png", # drop file here when downloaded
    "organizer": "/icons/organizer-onyok.png",     # drop file here when downloaded
}


def codepoints(emoji: str, keep_fe0f: bool, keep_skin: bool) -> str:
    parts = []
    for ch in emoji:
        cp = ord(ch)
        if cp == 0xFE0F and not keep_fe0f:
            continue
        if cp in SKIN_TONES and not keep_skin:
            continue
        parts.append(f"{cp:04X}")
    return "-".join(parts)


def try_download(emoji: str, slug: str) -> str | None:
    """Try filename variants (OpenMoji naming differs per emoji)."""
    variants = []
    for keep_fe0f in (False, True):
        for keep_skin in (True, False):
            cp = codepoints(emoji, keep_fe0f, keep_skin)
            if cp and cp not in variants:
                variants.append(cp)
    for cp in variants:
        url = CDN.format(cp)
        try:
            with urllib.request.urlopen(url, timeout=20) as r:
                data = r.read()
            out = OUT_DIR / f"{slug}.svg"
            out.write_bytes(data)
            print(f"  ok   {slug:<12} <- {cp}")
            return slug
        except Exception:
            continue
    print(f"  MISS {slug} (no OpenMoji file found)")
    return None


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print("Downloading OpenMoji icons (CC BY-SA 4.0)...")
    entries: list[tuple[str, str]] = []
    for emoji, spec in EMOJI.items():
        slug, art = (spec, emoji) if isinstance(spec, str) else spec
        if try_download(art, slug):
            entries.append((emoji, slug))

    lines = [
        "/* AUTO-GENERATED by tools/fetch_icons.py — edit freely, but re-running",
        "   the script overwrites this file.",
        "   Icons: OpenMoji (openmoji.org) - CC BY-SA 4.0. Attribution shown in",
        "   the main menu. Add your own files to public/icons/ and map them here. */",
        "",
        "export const ICON_OVERRIDES: Record<string, string | string[]> = {",
    ]
    for emoji, slug in entries:
        openmoji = f"/icons/openmoji/{slug}.svg"
        if slug in CUSTOM_FIRST:
            lines.append(f'  "{emoji}": ["{CUSTOM_FIRST[slug]}", "{openmoji}"],')
        else:
            lines.append(f'  "{emoji}": "{openmoji}",')
    lines.append("};")
    lines.append("")
    OVERRIDES_TS.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {len(entries)} overrides -> {OVERRIDES_TS}")


if __name__ == "__main__":
    main()
