/* AUTO-GENERATED by tools/fetch_icons.py — edit freely, but re-running
   the script overwrites this file.
   Icons: OpenMoji (openmoji.org) - CC BY-SA 4.0. Attribution shown in
   the main menu. Add your own files to public/icons/ and map them here. */

export const ICON_OVERRIDES: Record<string, string | string[]> = {
  "👨🏽‍🌾": ["/icons/farmer-ben.png", "/icons/openmoji/farmer.svg"],
  "👩🏽‍💼": ["/icons/storekeeper-lalay.png", "/icons/openmoji/storekeeper.svg"],
  "🕺🏽": ["/icons/organizer-onyok.png", "/icons/openmoji/organizer.svg"],
  "👦🏽": "/icons/openmoji/boy.svg",
  "👧🏽": "/icons/openmoji/girl.svg",
  "🧒🏽": "/icons/openmoji/child.svg",
  "👵🏽": "/icons/openmoji/lola.svg",
  "🎒": "/icons/openmoji/backpack.svg",
  "🦉": "/icons/openmoji/owl.svg",
  "🐿️": "/icons/openmoji/squirrel.svg",
  "🐇": "/icons/openmoji/rabbit.svg",
  "🐃": "/icons/openmoji/carabao.svg",
  "🦔": "/icons/openmoji/hedgehog.svg",
  "🐸": "/icons/openmoji/frog.svg",
  "🦌": "/icons/openmoji/deer.svg",
  "🐰": "/icons/openmoji/bunny-face.svg",
};
